Add instructions to include siva-java as a dependency with the latest version
src-d/siva-java pull request #16
Opened 2017-10-26 09:07 UTC by mcarmonaa

Changed the specific version `0.1.1` by `[version]` and added instructions to replace it with the latest version looking for it following the link to [maven central](http://search.maven.org/#search%7Cga%7C1%7Csiva-java).

2017-10-26 09:20 UTC, erizocosmico approved these changes

2017-10-26 09:23 UTC, ajnavarro approved these changes

2017-10-26 09:24 UTC, ajnavarro requested changes
You miss another version number on the line with the content:

> ./target/scala-2.11/siva-java_2.11-0.1.0-SNAPSHOT.jar

2017-10-26 09:42 UTC, mcarmonaa commented
@ajnavarro I already update that line, thanks to point it!

2017-10-26 09:46 UTC, ajnavarro approved these changes

2017-10-31 08:54 UTC, bzz approved these changes

2017-10-31 09:04 UTC, merged